server:
  port: 8090
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ebook?useSSL=false&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8
    username: ebook
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    #database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  resources:
    static-locations: classpath:/static

logging:
  path: ./logs

spider:
  coverPath: ./cover

app:
  app-version: 1.0.0