server:
  port: 8088
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/book?useSSL=false&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: Du87688524
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    open-in-view: false

  redis:
    host: 101.132.76.208
    port: 6379

logging:
  path: ./logs
