server:
  port: 8090
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://cdb-qx80diyu.cd.tencentcdb.com:10017/ebook?useSSL=false&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: Du87688524
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  resources:
    static-locations: classpath:/static

logging:
  file:
    path: ./logs

http-master:
  engine: httpClient

spider:
  coverPath: ./cover

app:
  app-version: 1.0.1

